import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import style from '../styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });
import Document from '../components/Document';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className=" mx-16"
        // className="bg-[url('/texture.jpg')] mx-8"
      >
        <Document />
      </main>
    </>
  );
}
